### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by banteg** [banteg/itf#3]
Post your questions or suggest new features here.
You can contact me directly [via Telegram](https://telegram.me/banteg).

**Comment by MrFloppie** [comment]
With the created binary it now works fine with the various playlist/chapter files. I just get the following notification:

```
Warning: Click detected the use of the unicode_literals __future__ import.
This is heavily discouraged because it can introduce subtle bugs in your code.
You should instead use explicit u"" literals for your unicode strings.
For more information see http://click.pocoo.org/python3/
```

Is this coming from the Python version deployed in Ubuntu (local paths suggest 2.7 rather than 3) or the script itself? 

Either way, right now I can't think of anything to improve it. I fear making a fancy GUI for it so even more unexperienced users than me can use it would draw too much attention to it so future downloads might become impossible due to counter measures. That would be a shame since each time there are a few very good artists in the line-up that never get Blu-ray concert releases or releases in general that are that well-produced quality-wise.

**Comment by banteg** [comment]
The warning comes from `click` library and suggests the script is running on Python 2.x. I haven't tested it on 2.7, but it should work just fine. Just ignore the warning.

On Ubuntu `pip` refers to Python 2.x pip. Python 3.x pip is called `pip3` and is not installed by default. These commands will install `pip3` and Python 3 version of `itf`:

```
sudo apt-get install python3-pip
sudo pip3 install -U itf
```

I completely share your concerns about drawing too much attention and that's why I never intend to make a fancy GUI or to distribute the script as a single binary. Last year the script supported an option to display all available gigs, this year I can't even MITM any of the apps to see where this metadata is coming from.

There is actually one thing to improve I can think of. Now the script downloads segments sequentially and immediately appends them to output file. I ended up with using the script to dump token and urls and downloading segments in parallel with `aria2c`. So I thought it might be a good idea to implement parallel downloading in the script itself. The problem is that I can't think of a method that works well on both 2.x and 3.x Python branches. Also it doesn't support resuming (but `aria2c` does), this can be improved, too.

**Comment by MrFloppie** [comment]
Is that the reason why for example when I open two separate Terminal windows simultaneously to download different gigs at once one of the downloads aborts - or is that something else?

**Comment by banteg** [comment]
No, it's something else. The script is not very clever and even if a singe segment fails it stops. I suggest you use `--dump` option and use aria2 for downloads. It supports much faster parallel downloading and resuming. You can install it with:

```
sudo apt-get install aria2
```

then use it like this:

```
aria2c -c -j 20 -d artist --header="Cookie: <contents of token.txt>" -i artist.urls
```

where `-j 20` is number of cocurrent downloads. When download completes, segments can be joined with simple concatenation:

```
cat artist/*.ts > artist.ts
```

**Comment by fgalvani70** [comment]
Hi banteg! Tks for the script! Works like a charm. Do you know where can I find the list of days and artists to use with your "itf" ?

**Comment by banteg** [comment]
Here's the full lineup:

19 andraday
19 elliegoulding
20 charlieputh 
20 take that
21 cam
21 theshires
21 carrieunderwood
22 littlemix
22 onedirection
23 gracemitchell
23 justineskye
23 theweeknd
24 hudsonmohawke
24 thechemicalbrothers
25 nao
25 lionbabe
25 disclosure
26 leonbridges
26 pharrellwilliams
27 jackgarratt
27 307699986_mumfordsons
28 florencethemachine

**Comment by fgalvani70** [comment]
Correction.... The Weekend played on 23th

_fixed it, thanks_

**Comment by Jakobud** [comment]
Funny I just came across this script after writing a similar one in Node.js last night. I was able to download all the .ts files for a show (Chemical Brothers) with my script however I can't seem to play any of them. I didn't know if the .ts files were encrypted or what. Any clues? 

I'll try this python file and see how that goes.

**Comment by banteg** [comment]
They are not encrypted, problem is that .ts (transport stream) files are not the end product. Basically they are just 10 second segments containing video and audio streams and could be joined with concatenation. So when you merge them to a large .ts file, it might be a good idea to remux it to .mp4 with Yamb or Subler to get better compatibility without affecting real audio/video streams.

**Comment by Jakobud** [comment]
Well I just used your script and it worked great. Thanks!

Regarding the .ts files, yeah I understand that they are individual chunks that have to be concatenated together. Is each individual .ts file/chunk playable on its own? Or is the .ts file not playable until you concat all of them together and then it is a complete file? Just curious for my own learning.

**Comment by banteg** [comment]
Yes, they are playable on their own and could be merged with a simple `cat`.

**Comment by banteg** [comment]
Hey everyone! I've added multithreaded downloading with on-the-fly merging. Script now works **insanely** fast. There's new option called `--threads` (or `-j`) for selecting number of parallel threads (1–1000, default is 20). Please update with:

```
pip install -U itf
```

**Comment by cris-pin** [comment]
**Thank-you!** Love the updated version, faster and still as _awesome_ as ever

**Comment by MrFloppie** [comment]
Updating doesn't work on my system (Debian x64 latest stable release): Using Terminal as root via su -l before executing:

```
pip3 install -U itf
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip3')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python3/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name 'IncompleteRead'
```

Any idea what that might be? "apt-get install python3-pip" shows that the latest version of Python 3 is already installed.

**Comment by banteg** [comment]
Here's discussion of your problem:
http://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread

**Comment by Skyross** [comment]
HI!
At first: thank you for awesome tool and I discovered useful `click` package for me :)
But I have a problem with videos - they randomly freezing and sometimes audio dissapear. May it caused by some issue in code or it's just problems with TS type?
Also, I have a question about video conversion on Linux platform. Do you have any ideas about?

**Comment by banteg** [comment]
It's a known issue with `.ts` format. On Linux you could give `mp4box` a try, it's used in Yamb behind the scenes, so I think it should do the job fine.

**Comment by Skyross** [comment]
@banteg Thank you for this fast reply! I've tried `mp4box` and got this errors:

```
[MPEG-2 TS] PES 257: Duplicated Packet found (CC 9) - skipping
[MPEG-2 TS] PID 257 PES payload size 21882 but received 14338 bytes
[MPEG-2 TS Import] PID 258: Error adding sample: Bad Parameter
Error importing 26_961252454_leonbridges_1080p.ts: Bad Parameter
```

Can it be caused by failed requests via proxy?
I've tried to convert `ac3` to `mp4` and it's done without any delays in audio.

**Comment by banteg** [comment]
I've tried it on Ubuntu server and the resulting file plays just fine. Here's the output:

```
$ itf 26 leonbridges
Downloading 195 parts to 26_961252454_leonbridges_1080p.ts
  [####################################]  195/195
Done! Enjoy the show.

$ MP4Box -add 26_961252454_leonbridges_1080p.ts -new leonbridges.mp4
[MPEG-2 TS] Stream type (0x15) for PID 258 not supported
Importing MPEG-2 TS (PID 256)
[MPEG-2 TS] Stream type (0x15) for PID 258 not supported
MPEG-4 AVC/H264 Video import (TS PID 256)
Importing MPEG-2 TS (PID 257)
[MPEG-2 TS] Stream type (0x15) for PID 258 not supported
MPEG-4 AAC Audio import - SampleRate 48000 Channels 2 Language .... (TS PID 257)
Timeline offset: 6 ms
Saving out.mp4: 0.500 secs Interleaving
```

The warning here is caused by metadata stream (timed_id3) and can be ignored. Your problem can definitely be caused by failed requests, so I've updated the script to retry on connection failures (but it still expects good network conditions). If this update doesn't help, you should try `aria2c` method [described above](https://github.com/banteg/itf/issues/3#issuecomment-142439527).

**Comment by outaTiME** [comment]
still working ?? im getting "Recoding not available" :cry:

**Comment by outaTiME** [comment]
Finally i could download all shows, here the complete and working list:

19 elliegoulding
19 677081663_andraday
20 takethat
20 charlieputh
21 carrieunderwood
21 theshires
21 cam
22 onedirection
22 littlemix
23 theweeknd
23 gracemitchell
23 justineskye
24 thechemicalbrothers
24 hudsonmohawke
25 disclosure
25 nao
25 lionbabe
26 pharrellwilliams
26 leonbridges
27 307699986_mumfordsons
27 jackgarratt
28 florencethemachine

Note: the `20 charlieputh` ac3 is partial download, i dont know why @banteg ... but is the only "ac3" file to get chopped, you can check that (the download size is 15.6 MB)

**Comment by MrFloppie** [comment]
@outaTiME 
You were able to download the shows today?!
I always thought they are deleted as two months after the first concert originally aired.
Getting some shows from 2011 to 2013 would be awesome.
